### ISSUE TITLE
send is ok, but get is wrong.

### ISSUE THREAD

**Issue by genics** [Digiography/blender_addon_rizom_uv#2]
i think the addon import wrong files when i click the import button, the uv no change. it load the Sphere_ruv.fbx not the Sphere_ruv_out.fbx. pls check it.

**Comment by DigiKrafting** [comment]
The addon only creates {filename/object}_ruv.fbx, it does not create a {filename/object}_ruv_out.fbx. There is no way for blender to know if you save under a different filename from RizomUV, you need to save/overwrite Sphere_ruv.fbx when finished in RizomUV and the addon will import the updated UV's.  I'm using RizomUV  2018.0.171 and it does not change the filename.

**Comment by genics** [comment]
ok. it work now, this is rizomuv's fault
